### ISSUE TITLE
Implementación de la funcionalidad de Viaje Plus

### ISSUE THREAD

**Issue by valennat** [thelmamedran/TrabajoSube#2]
- El "Viaje Plus" permite a los usuarios realizar viajes incluso si su tarjeta se queda sin crédito, con un saldo negativo máximo de hasta $211.84. Cuando el usuario recargue su tarjeta, el sistema debe descontar el saldo utilizado en concepto de viaje plus.

- Escribir un test que valide que la tarjeta no pueda quedar con menos saldo que el permitido.

- Escribir un test que valide que el saldo de la tarjeta descuenta correctamente el/los viaje/s plus otorgado/s.

**Comment by thelmamedran** [comment]
**### _esta perfecto_**
